package com.pinkman.dtboot.dao;

import com.pinkman.dtboot.entity.ScheduleJob;
import com.pinkman.dtboot.utils.Query;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component(value ="scheduleJobMapper")
public interface ScheduleJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated
     */
    int insert(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated
     */
    int insertSelective(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated
     */
    ScheduleJob selectByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScheduleJob record);

    List<ScheduleJob> queryList(Query query);

    int queryTotal(Query query);

    int deleteBatch(Long[] scheduleJobIds);

    /**
     * 批量更新状态
     */
    int updateBatch(Map<String, Object> map);
}