package com.pinkman.dtboot.dao;

import com.pinkman.dtboot.entity.SysMenu;
import com.pinkman.dtboot.utils.Query;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    SysMenu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysMenu record);

    /**
     * @description: 查询所有记录
     * @param
     * @return: java.util.List<com.pinkman.dtboot.entity.SysMenu>
     */
    List<SysMenu> queryListAll();

    /**
     * @description: 根据查询参数查询
     * @param query
     * @return: java.util.List<com.pinkman.dtboot.entity.SysMenu>
     */
    List<SysMenu> queryList(Query query);

    /**
     * @description:  查询总记录数
     * @param
     * @return: int
     */
    int queryTotal();

    /**
     * @description: 批量删除
     * @param id
     * @return: int
     */
    int deleteBath(Long[] id);
}