package com.pinkman.dtboot.dao;

import com.pinkman.dtboot.entity.SysUser;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "sysUserMapper")
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    SysUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUser record);

    /**
     * @description: 根据用户名查找用户信息
     * @param username
     * @return: com.pinkman.dtboot.entity.SysUser
     */
    SysUser queryByUserName(String username);

    /**
     * @description: 根据userId获取用户的所有权限
     * @param userId
     * @return: java.util.List<java.lang.String>
     */
    List<String> queryAllPermsById(Long userId);

    /**
     * @description: 根据userId获取用户具有权限的所有菜单列表
     * @param userId
     * @return: java.util.List<java.lang.Long>
     */
    List<Long> queryAllMenuIdByUserId(Long userId);
}